name: Automatic Cricsheet Update

on:
  schedule:
    - cron: '0 2 * * *'

  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Python Libraries
        run: pip install kaggle requests

      - name: Setup Kaggle Credentials
        run: |
          mkdir -p ~/.kaggle
          echo '{"username":"${{ secrets.KAGGLE_USERNAME }}","key":"${{ secrets.KAGGLE_KEY }}"}' > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json

      - name: Run Data Download Script
        run: python download_data.py
