name: Automatic Cricsheet Update

on:
  schedule:
    - cron: '0 2 * * *'

  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Libraries
        run: pip install kaggle requests
      
      - name: Setup Kaggle API
        run: |
          mkdir -p ~/.kaggle
          echo "${{ secrets.KAGGLE_API_TOKEN }}" > ~/.kaggle/access_token
          chmod 600 ~/.kaggle/access_token


      - name: Run Script
        run: python download_data.py
